//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureService.Clients.ConsoleClient.SecureUserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecureUserServiceReference.ISecureUserService")]
    public interface ISecureUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureUserService/GetData", ReplyAction="http://tempuri.org/ISecureUserService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureUserService/GetData", ReplyAction="http://tempuri.org/ISecureUserService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecureUserServiceChannel : SecureService.Clients.ConsoleClient.SecureUserServiceReference.ISecureUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecureUserServiceClient : System.ServiceModel.ClientBase<SecureService.Clients.ConsoleClient.SecureUserServiceReference.ISecureUserService>, SecureService.Clients.ConsoleClient.SecureUserServiceReference.ISecureUserService {
        
        public SecureUserServiceClient() {
        }
        
        public SecureUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecureUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
