USE [master]
GO
/****** Object:  Database [MyDeadlockedDb]    Script Date: 02-04-2018 23:19:29 ******/
CREATE DATABASE [MyDeadlockedDb]
GO
ALTER DATABASE [MyDeadlockedDb] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyDeadlockedDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyDeadlockedDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyDeadlockedDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyDeadlockedDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyDeadlockedDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyDeadlockedDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MyDeadlockedDb] SET  MULTI_USER 
GO
ALTER DATABASE [MyDeadlockedDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyDeadlockedDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyDeadlockedDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyDeadlockedDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MyDeadlockedDb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MyDeadlockedDb]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 02-04-2018 23:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Balance] [decimal](18, 4) NOT NULL CONSTRAINT [DF_Account_Balance]  DEFAULT ((0)),
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[User]    Script Date: 02-04-2018 23:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Account] ON 

GO
INSERT [dbo].[Account] ([Id], [Balance], [UserId]) VALUES (1, CAST(158.0000 AS Decimal(18, 4)), 1)
GO
INSERT [dbo].[Account] ([Id], [Balance], [UserId]) VALUES (2, CAST(420.0000 AS Decimal(18, 4)), 2)
GO
INSERT [dbo].[Account] ([Id], [Balance], [UserId]) VALUES (3, CAST(256.0000 AS Decimal(18, 4)), 1)
GO
SET IDENTITY_INSERT [dbo].[Account] OFF
GO
SET IDENTITY_INSERT [dbo].[User] ON 

GO
INSERT [dbo].[User] ([Id], [Name]) VALUES (1, N'Ronni H')
GO
INSERT [dbo].[User] ([Id], [Name]) VALUES (2, N'Jens J')
GO
INSERT [dbo].[User] ([Id], [Name]) VALUES (3, N'John Doe')
GO
SET IDENTITY_INSERT [dbo].[User] OFF
GO
ALTER TABLE [dbo].[Account]  WITH CHECK ADD  CONSTRAINT [FK_Account_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Account] CHECK CONSTRAINT [FK_Account_User]
GO
USE [master]
GO
ALTER DATABASE [MyDeadlockedDb] SET  READ_WRITE 
GO
